/**
 * Static PWA build: turns the Apps Script partials into the installable app.
 *
 * App.html + Styles.html + Script.html stay the single source of truth and keep
 * serving the Apps Script web app untouched. This derives www/ from them for a
 * static host. Nothing here rewrites application logic: the one behavioural
 * switch between the two hosts is `window.AK_EXEC`, set in the generated
 * index.html before app.js loads, which flips call() in Script.html from the
 * google.script.run bridge to fetch.
 *
 *   node dev/build.mjs            build www/
 *   node dev/build.mjs --serve    build, then serve www/ on :4600 (rebuilds per request)
 *   AK_EXEC=http://localhost:4599/api node dev/build.mjs --serve
 *                                 same, but the bundle talks to the dev harness
 *   AURA_BASE=http://localhost:8000 node dev/build.mjs --serve
 *                                 same, plus the Aura chat button, pointed at a
 *                                 locally running aura-chat service
 *
 * Optional inputs, picked up when present:
 *   assets/icons/*.png            app icons (see the plan's icon table)
 *   assets/splash-links.html      <link rel="apple-touch-startup-image"> tags
 *                                 from pwa-asset-generator
 */
import { readFile, writeFile, mkdir, rm, readdir, copyFile, access } from 'node:fs/promises';
import { createServer } from 'node:http';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { EXEC, AURA } from './config.mjs';

const ROOT = new URL('..', import.meta.url);
const OUT = new URL('www/', ROOT);
const ASSETS = new URL('assets/', ROOT);

const read = (rel, base = ROOT) => readFile(new URL(rel, base), 'utf8');
const exists = (rel, base = ROOT) => access(new URL(rel, base)).then(() => true, () => false);

/* The body of a single-element wrapper, e.g. the <style>…</style> of Styles.html. */
function unwrap(src, tag, file) {
  const open = src.indexOf('<' + tag);
  const gt = open === -1 ? -1 : src.indexOf('>', open);
  const close = src.lastIndexOf('</' + tag + '>');
  if (gt === -1 || close === -1 || close < gt) throw new Error(file + ': expected one <' + tag + '> wrapper');
  return src.slice(gt + 1, close).trim() + '\n';
}

// Sizes live in manifest() and in the filenames; apple-touch-icon is the only one iOS reads.
const ICONS = ['apple-touch-icon.png', 'icon-192.png', 'icon-512.png', 'icon-512-maskable.png'];

/* Sign-in artwork, served from the bundle root because that is what the CSS asks for.
   Apps Script has nowhere to put binaries, so there it 404s and the gate falls back to
   its scrim and radial — by design, not by accident. The logo is inline SVG now, so
   the photograph is the only binary the sign-in screen needs. */
const GATE_ASSETS = ['gate.jpg'];

/* Only icons that actually shipped are advertised: a manifest pointing at a 404
   fails Android's install check silently, and iOS pins a screenshot instead. */
function manifest(icons) {
  const has = (f) => icons.includes(f);
  return JSON.stringify({
    id: '/',
    name: 'Aura Key',
    short_name: 'Aura Key',
    description: 'Aura Key Realty realtor tools',
    start_url: '/#home',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    theme_color: '#0E1A22',
    background_color: '#0E1A22',
    icons: [
      has('icon-192.png') && { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      has('icon-512.png') && { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
      has('icon-512-maskable.png') && { src: 'icons/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ].filter(Boolean),
  }, null, 2) + '\n';
}

/* App-shell service worker. It owns only this origin: the API on script.google.com
   is never intercepted, so a request that fails still *rejects* in call() and the
   offline fallback in Script.html stays the offline fallback. Data lives in
   localStorage, not here. */
function serviceWorker(version, required, optional) {
  return `/* generated by dev/build.mjs — do not edit */
var CACHE = 'ak-shell-${version}';
var REQUIRED = ${JSON.stringify(required)};
var OPTIONAL = ${JSON.stringify(optional)};

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) {
    // cache:'reload' bypasses the HTTP cache so a new worker never precaches a stale file.
    // The shell is fetched as one unit: if any part fails, install fails, the previous
    // worker keeps serving its complete cache, and the next load retries. A half-cached
    // shell that took over would work online and be a blank page offline.
    return c.addAll(REQUIRED.map(function (u) { return new Request(u, { cache: 'reload' }); })).then(function () {
      return Promise.all(OPTIONAL.map(function (u) {
        return c.add(new Request(u, { cache: 'reload' })).catch(function () { /* icon or splash not shipped yet */ });
      }));
    });
  }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k !== CACHE && k.indexOf('ak-shell-') === 0; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // never the API, never the fonts
  var key = req.mode === 'navigate' ? 'index.html' : url.pathname.replace(/^\\//, '');
  e.respondWith(caches.match(key).then(function (hit) {
    return hit || fetch(req).then(function (res) {
      if (res.ok) { var copy = res.clone(); caches.open(CACHE).then(function (c) { c.put(key, copy); }); }
      return res;
    });
  }));
});
`;
}

/* Registers the worker and reloads once when a *replacement* takes over, so a
   deploy reaches an open app without anyone hard-refreshing. Not on first install:
   there is no controller to replace, and a reload would just flash the gate. */
const REGISTER = `<script>
if ('serviceWorker' in navigator && window.AK_EXEC) {
  var had = !!navigator.serviceWorker.controller, done = false;
  navigator.serviceWorker.addEventListener('controllerchange', function () { if (had && !done) { done = true; location.reload(); } });
  window.addEventListener('load', function () { navigator.serviceWorker.register('sw.js').catch(function () {}); });
}
</script>`;

export async function build(exec = EXEC, aura = AURA) {
  const app = await read('App.html');
  const css = unwrap(await read('Styles.html'), 'style', 'Styles.html');
  const js = unwrap(await read('Script.html'), 'script', 'Script.html');

  const includes = [...app.matchAll(/<\?!=\s*include\('([^']+)'\)\s*\?>/g)];
  const names = includes.map((m) => m[1]);
  if (names.length !== 2 || !names.includes('Styles') || !names.includes('Script')) {
    throw new Error('App.html: expected includes for Styles and Script, found [' + names + ']');
  }

  // Optional assets
  const icons = [];
  for (const file of ICONS) if (await exists('icons/' + file, ASSETS)) icons.push(file);
  const splash = (await exists('splash-links.html', ASSETS)) ? await read('splash-links.html', ASSETS) : '';
  const splashFiles = splash ? await readdir(new URL('splash/', ASSETS)).catch(() => []) : [];
  const gateAssets = [];
  for (const file of GATE_ASSETS) if (await exists(file, ASSETS)) gateAssets.push(file);
  const favicon = (await exists('icons/favicon.svg', ASSETS)) ? 'favicon.svg' : (await exists('icons/favicon.png', ASSETS)) ? 'favicon.png' : '';

  // A deploy without icons is not installable, and www/ is gitignored so nothing
  // reviews it: fail here, before `netlify deploy` can ship it. Local --serve and an
  // explicit flag (draft deploys) are the only ways past.
  const missing = ICONS.filter((f) => !icons.includes(f));
  const lenient = process.argv.includes('--serve') || process.argv.includes('--allow-missing-icons');
  if (missing.length && !lenient) {
    throw new Error('missing icons: ' + missing.join(', ') + ' — add them to assets/icons/ or pass --allow-missing-icons');
  }

  const head = [
    '<title>Aura Key</title>',
    '<link rel="manifest" href="manifest.json">',
    icons.includes('apple-touch-icon.png') ? '<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">' : '',
    favicon ? '<link rel="icon" href="icons/' + favicon + '">' : '',
    splash.trim(),
    '<link rel="stylesheet" href="app.css">',
  ].filter(Boolean).join('\n');

  let index = app;
  for (const [tag, name] of includes) {
    index = index.replace(tag, () => name === 'Styles'
      ? head
      : '<script>window.AK_EXEC=' + JSON.stringify(exec)
        // Empty string is falsy, so an unset AURA_BASE leaves auraReady() false
        // and the chat button hidden. Only a real service URL turns it on.
        + ';window.AURA_BASE=' + JSON.stringify(aura) + ';</script>\n'
        + '<script src="app.js"></script>\n' + REGISTER);
  }
  // <base target="_top"> routes the sandboxed Apps Script iframe's untargeted links
  // (tel:, mailto:) to the top-level page. It has no href, so it never touched URL
  // resolution; in a top-level document it is simply meaningless, and stripping it
  // keeps the shipped shell honest. Asserted, like the include check above, so a
  // reformat of App.html shows up here rather than as 21 stale bytes in every build.
  const beforeBase = index;
  index = index.replace(/^\s*<base target="_top">\s*\n?/m, '');
  if (index === beforeBase) throw new Error('App.html: expected <base target="_top"> to strip');

  const iconFiles = icons.concat(favicon ? [favicon] : []);
  const mf = manifest(icons);

  // One hash over everything the worker will pin: a new deploy is a new cache. The
  // worker is cache-first with no revalidation, so anything left out of this digest
  // -- the manifest text, an icon's bytes -- would be served stale to installed
  // clients forever, because sw.js itself would not change and never reinstall.
  const h = createHash('sha256').update(index).update(css).update(js).update(mf);
  for (const f of iconFiles) h.update(f).update(await readFile(new URL('icons/' + f, ASSETS)));
  for (const f of splashFiles) h.update(f).update(await readFile(new URL('splash/' + f, ASSETS)));
  for (const f of gateAssets) h.update(f).update(await readFile(new URL(f, ASSETS)));
  const version = h.digest('hex').slice(0, 10);

  const required = ['index.html', 'app.css', 'app.js', 'manifest.json'];
  const optional = iconFiles.map((f) => 'icons/' + f).concat(splashFiles.map((f) => 'splash/' + f)).concat(gateAssets);

  await rm(OUT, { recursive: true, force: true });
  await mkdir(new URL('icons/', OUT), { recursive: true });
  await writeFile(new URL('index.html', OUT), index);
  await writeFile(new URL('app.css', OUT), css);
  await writeFile(new URL('app.js', OUT), js);
  await writeFile(new URL('manifest.json', OUT), mf);
  await writeFile(new URL('sw.js', OUT), serviceWorker(version, required, optional));
  for (const f of iconFiles) await copyFile(new URL('icons/' + f, ASSETS), new URL('icons/' + f, OUT));
  for (const f of gateAssets) await copyFile(new URL(f, ASSETS), new URL(f, OUT));
  if (splashFiles.length) {
    await mkdir(new URL('splash/', OUT), { recursive: true });
    for (const f of splashFiles) await copyFile(new URL('splash/' + f, ASSETS), new URL('splash/' + f, OUT));
  }

  const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + ' KB';
  console.log('built www/  (shell ' + version + ')');
  console.log('  index.html ' + kb(index) + '   app.css ' + kb(css) + '   app.js ' + kb(js));
  console.log('  icons: ' + (icons.length ? icons.join(', ') : 'NONE — drop PNGs in assets/icons/'));
  console.log('  gate:  ' + (gateAssets.length ? gateAssets.join(', ') : 'NONE — gradient + AK tile fallback'));
  console.log('  splash: ' + (splash ? 'yes' : 'none') + '   API → ' + exec);
  return version;
}

const TYPES = { html: 'text/html; charset=utf-8', css: 'text/css', js: 'text/javascript', json: 'application/manifest+json', png: 'image/png', svg: 'image/svg+xml', jpg: 'image/jpeg', jpeg: 'image/jpeg' };

async function serve(port) {
  createServer(async (req, res) => {
    try {
      let p = new URL(req.url, 'http://x').pathname;
      if (p === '/') { await build(); p = '/index.html'; }   // rebuild on each page load: edit, reload
      const body = await readFile(new URL('.' + p, OUT));
      res.writeHead(200, { 'content-type': TYPES[p.split('.').pop()] || 'application/octet-stream', 'cache-control': 'no-store' });
      res.end(body);
    } catch (err) { res.writeHead(404); res.end('not found'); }
  }).listen(port, () => console.log('PWA bundle on http://localhost:' + port));
}

// Compared as full URLs, not basenames: dev/deploy.mjs imports build() from here,
// and a basename match would be wrong for any wrapper that entered another file.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await build();
  if (process.argv.includes('--serve')) await serve(4600);
}
