"""Unbrander's domain: PDF facts, the edit vocabulary and the verification result."""

from .actions import (
    KEPT_KINDS,
    PAGE_KINDS,
    PLAN_KINDS,
    Action,
    AddMark,
    Brief,
    DropPage,
    Outcome,
    PageKind,
    PageSort,
    PageView,
    RedactRect,
    RedactTerms,
    RemoveElement,
    Sorting,
    Usage,
)
from .edit import (
    DrawnElement,
    Finished,
    GridBox,
    MarkPosition,
    NumberedElement,
    Removal,
    TermsResult,
    ToolRejected,
    from_box_2d,
    to_box_2d,
)
from .pdf import OCR_MODES, BBox, PageFacts, Paint, PdfFacts, Thumbnail, Word
from .terms import EMAIL, PHONE, SHORT, term_pattern
from .text import area, intersects, joined, missing, overlap, union, words_in_span
from .verify import Check, Finding, HitList, Severity, VerifyReport

__all__ = [
    "EMAIL",
    "KEPT_KINDS",
    "OCR_MODES",
    "PAGE_KINDS",
    "PHONE",
    "PLAN_KINDS",
    "SHORT",
    "Action",
    "AddMark",
    "BBox",
    "Brief",
    "Check",
    "DrawnElement",
    "DropPage",
    "Finding",
    "Finished",
    "GridBox",
    "HitList",
    "MarkPosition",
    "NumberedElement",
    "Outcome",
    "PageFacts",
    "PageKind",
    "PageSort",
    "PageView",
    "Paint",
    "PdfFacts",
    "RedactRect",
    "RedactTerms",
    "Removal",
    "RemoveElement",
    "Severity",
    "Sorting",
    "TermsResult",
    "Thumbnail",
    "ToolRejected",
    "Usage",
    "VerifyReport",
    "Word",
    "area",
    "from_box_2d",
    "intersects",
    "joined",
    "missing",
    "overlap",
    "term_pattern",
    "to_box_2d",
    "union",
    "words_in_span",
]
